### ISSUE TITLE
cargo test not capturing log outputs

### ISSUE THREAD

**Issue by liangyongrui** [env-logger-rs/env_logger#150]
like #107 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0aa41ea6690fb25c0b60004fa80e8045

I used the example in readme, but still no output.

**Comment by KodrAus** [comment]
Hey @liangyongrui :wave:

Sorry for taking so long to circle around to this! There are two things going on in that sample:

1. The log events are captured by `cargo test`, which only shows them for tests that fail, unless you pass the `--nocapture` flag.
2. The default environment variable will only show error and above events, so when running `cargo test` you either need an environment variable like `RUST_LOG=info`, or add a `.filter_level(log::LevelFilter::Info)` to your builder.
