### ISSUE TITLE
Module path and target confusion

### ISSUE THREAD

**Issue by geigerzaehler** [env-logger-rs/env_logger#155]
The “Enabling logging” section of the documentation states that the module path is used to filter logging statements. But in fact the target of a logging record  (which defaults to the module path) is used for filtering.

In addition the default formatter prints the module path and not the target. This lead to some confusion for me when I tried to write a filter based on the output I was seeing.

It would be great if the documentation would be corrected and ideal if the target was printed by the default formatter.

**Comment by Pand9** [comment]
Just went to create this issue as well. I only discovered this behavior by asking around on Discord and it's a game changing feature.

**Comment by jplatte** [comment]
@KodrAus what are your thoughts? We could also adjust the default formatting, as suggested in #179.

**Comment by KodrAus** [comment]
I'd be up for updating the default format to avoid this kind of confusion :+1:
