### ISSUE TITLE
Systemd format support

### ISSUE THREAD

**Issue by matteomaser** [env-logger-rs/env_logger#157]
I have a Linux service which I run using Systemd. I really like logging to stdout as it is convenient during development.  
Since Systemd supports capturing logs directly from stderr/stdout, I've decided to keep using env_logger rather than the [systemd](https://github.com/jmesmon/rust-systemd) or [syslog](https://github.com/Geal/rust-syslog) crates.

By default the log format is not usable since it creates duplicate information and doesn't keep the log urgency.
```
Mar 16 15:08:01 raspberrypi my_daemon[7697]: [2020-03-16T14:08:01Z WARN  my_daemon::storage] <actual log message...>
```

A better solution is to strip the timestamp and pass the log level to systemd (it uses a `<level>` prefix format):

```rust
fn main() {
    match std::env::var("RUST_LOG_STYLE") {
        Ok(s) if s == "SYSTEMD" => env_logger::builder()
            .format(|buf, record| {
                writeln!(
                    buf,
                    "<{}>{}: {}",
                    match record.level() {
                        log::Level::Error => 3,
                        log::Level::Warn => 4,
                        log::Level::Info => 6,
                        log::Level::Debug => 7,
                        log::Level::Trace => 7,
                    },
                    record.target(),
                    record.args()
                )
            })
            .init(),
        _ => env_logger::init(),
    };
}
```

My feature request is to integrate it natively in env_logger, since I see some synergy here between the two projects.

Feel free to close the issue if you don't think this is a good idea. I'll leave the code snippet here for posterity, maybe someone else will find it useful.

Thanks for env_logger!

**Comment by KodrAus** [comment]
Hi @matteomaser :wave:

I think it would be great to add this format as an example to the repo if you're happy to do that :+1:
