### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by Veetaha** [env-logger-rs/env_logger#159]
@sebasmagri might I ask you whether you are still interested in maintaining this crate and if you'd like to pass the maintenance to anyone else?

**Comment by Veetaha** [comment]
cc @KodrAus

**Comment by sebasmagri** [comment]
For a long time @KodrAus has been the main maintainer of the project. So actually I'd be fine passing the _maintenance/ownership_ of the project to him or someone he agrees on.

**Comment by jplatte** [comment]
This crate is pretty popular, I am surprised it is hardly maintained :/

@KodrAus is this on your todo list?

**Comment by KodrAus** [comment]
It is on my todo list (along with `bitflags`and `uuid`). Unfortunately it’s been a really big year and it hasn’t managed to find its way to the top yet. I’d be up for creating a `env_logger_rs` org on GitHub and moving the project into it so it’s easy to add contributors and people with publish rights.

If I create the org would you be happy to migrate @sebasmagri?

**Comment by KodrAus** [comment]
In the meantime I'll do a pass through all the open PRs :eyes:

**Comment by sebasmagri** [comment]
Yes absolutely @KodrAus! 100% up to make it easier to onboard new collaborators.

**Comment by SirWindfield** [comment]
If you guys need help on PRs and issue management, I can help out :) I do already do this for a lot of Rust projects (the biggest one being `spotifyd`).

**Comment by KodrAus** [comment]
@sebasmagri @SirWindfield I've created an `env-logger-rs` repository and invited you both to it 🙂 I've opened #163 to track our progress migrating the repository into that org

**Comment by SirWindfield** [comment]
Awesome! Thank you!

**Comment by KodrAus** [comment]
@sebasmagri I think you’re the only one who’s got permission to move the repository 🙂

**Comment by kornelski** [comment]
The last release has been almost a year ago. It'd be nice to release latest changes.

**Comment by SirWindfield** [comment]
We don't have publishing rights, they haven't been granted to us. @kornelski

**Comment by kornelski** [comment]
:(

@alexcrichton @sfackler and @huonw also have crates-io ownership. Maybe they can help?

**Comment by SirWindfield** [comment]
If they wouldn't mind. We wanted to have the whole publisher team have access to publishing, so they'd have to run this command:
```
cargo owner --add github:env-logger-rs:publishers
```

**Comment by sebasmagri** [comment]
I tried last time and crates.io gave me some error. Will try again.

**Comment by SirWindfield** [comment]
No clue. But I can figure it out. You could add me for now. That way I can see what is wrong there and try to add the team myself.

**Comment by kornelski** [comment]
I think github has privacy control around team's existence and membership. You may need to log in to crates-io again and grant it access to the env-logger-rs org, so that it can scan its teams.

**Comment by SirWindfield** [comment]
@kornelski Ah! Did re-log and granted crates.io access to @env-logger-rs. At least crates.io is listed under authorized apps now :)

**Comment by sebasmagri** [comment]
That apparently did it! Thanks @kornelski

**Comment by Veetaha** [comment]
I'd just recommend adding publishing to CI like [that](https://github.com/borntyping/rust-simple_logger/blob/adab500b4d7ca08a2a42dbc2030f89cbdf643239/.github/workflows/ci.yml#L56-L70)

This makes the process of publishing more automated (you just push a new git tag), and more transparent (the publisher won't inject malicious code before publishing the crate).

**Comment by jplatte** [comment]
The maintenance issues have been addressed. I'm personally not sure what to think of the CI publishing suggestion, but in any case that seems like it should be a separate issue.

**Comment by jplatte** [comment]
This project has once again run out of (active) maintainers, it seems. I'm no longer using env_logger so while I'm definitely still very active in the Rust community overall, it's hard to justify spending time on this.

**Comment by Veetaha** [comment]
@jplatte are you using `tracing` now? I think `log` gets pushed back more and more by `tracing`, thus that's understandable

**Comment by jplatte** [comment]
Yes, I've been exclusively using tracing(-subscriber) instead of log / env_logger for quite a while now.

**Comment by epage** [comment]
@jplatte One option: the CLI-WG helps "keep the lights on" for important CLI-related crates. I think this one counts if you are up for adding us as maintainers.

**Comment by jplatte** [comment]
@epage that's great, I've added you as an org owner. Please do kick me out of the org once you have confirmed that everything works and add other people, or just move the repo to another org like rust-lang-nursery if that makes sense to you. The list of people who can publish this crate on crates.io is very long and it probably makes sense to cut it down a bit to those who are actually somewhat likely to be involved with the project in the future.

**Comment by jplatte** [comment]
Not sure why epage didn't do it yet, but I'm now removing myself from the org with [v0.9.2](https://github.com/env-logger-rs/env_logger/releases/tag/v0.9.2) released.
