### ISSUE TITLE
fix docs workflow

### ISSUE THREAD

**Issue by SirWindfield** [env-logger-rs/env_logger#172]
Currently, I can't access the url at http://env-logger-rs.github.io/env_logger and I am not sure why, as this should be the URL that the `gh-pages` branch can be accessed from.

**Comment by jplatte** [comment]
It works if you append `/index.html` manually: https://env-logger-rs.github.io/env_logger/index.html

Seems like this has been a problem for others before and it might just randomly fix itself after a few deployments: https://stackoverflow.com/questions/45362628/github-pages-site-not-detecting-index-html

**Comment by SirWindfield** [comment]
Ahhhh! Thank you very much! I didn't think about adding the index file to it! Maybe the `ci` crate shouldn't be documented though :)

**Comment by jplatte** [comment]
To only document `env_logger` itself, we can just use `cargo doc -p env_logger`.

**Comment by SirWindfield** [comment]
Fixed!

> To only document `env_logger` itself, we can just use `cargo doc -p env_logger`

Turns out I passed `--workspace`, which is in most of my libraries right but here wrong :)
