### ISSUE TITLE
Log with target instead of module path by default?

### ISSUE THREAD

**Issue by inferiorhumanorgans** [env-logger-rs/env_logger#179]
The`log` macro sets the target to the module path by default but only allows users to override the target.  By using the target instead of the module path in the default formatter an end user could trivially modify the default format.

Thoughts?

**Comment by jplatte** [comment]
I'm not certain I understand the full implications of this change. @KodrAus wdyt?

**Comment by KodrAus** [comment]
It sounds like it is confusing that we're using the module path instead of the target, especially since they're _usually_ the same.

I'd be happy to change the default format to use the target instead.
