### ISSUE TITLE
Travis CI badge in Readme says unknown repository

### ISSUE THREAD

**Issue by atouchet** [env-logger-rs/env_logger#187]
The Travis CI badge in the Readme says unknown and when clicked it directs to a page saying "We couldn't display the repository
env-logger-rs/env_logger". Is this no longer used?

**Comment by jplatte** [comment]
Right, we're using GitHub Actions now.

**Comment by jplatte** [comment]
I've removed the badge. I'm not sure we need one for GA, other places on the repo already show the CI status and I think for crates.io there is a different way of integrating badges.
