### ISSUE TITLE
Obsolete copyright info

### ISSUE THREAD

**Issue by atouchet** [env-logger-rs/env_logger#220]
https://github.com/env-logger-rs/env_logger/blob/52a3e69b38f69469b77502651992f91bdfebb48a/src/lib.rs#L1-L3

There is no COPYRIGHT file in this repo nor does the copyright URL still work. Should these lines be removed/changed?

**Comment by jplatte** [comment]
"The Rust Project Developers" is also not a legal entity that can hold copyright. I'll remove this.

**Comment by jplatte** [comment]
38643a3
