### ISSUE TITLE
Add git tags to released versions

### ISSUE THREAD

**Issue by laumann** [env-logger-rs/env_logger#51]
It'd be nice if tags were created for each released version, to make the specific commits easier to find.

**Comment by KodrAus** [comment]
Thanks @laumann :+1: Sorry I forgot to tag the latest RC release!

**Comment by KodrAus** [comment]
I've added a [tagged release for `0.5.0-rc.2`](https://github.com/sebasmagri/env_logger/releases/tag/v0.5.0-rc.2)

**Comment by laumann** [comment]
Nice, I was looking for older versions, both for the 0.3.x and 0.4.x - would you add tags for those as well?

**Comment by laumann** [comment]
I'm liking the detailed release notes, it's good :+1:

**Comment by KodrAus** [comment]
@laumann No problem, when I find a little downtime, I'll go through and add tags for the previous releases :+1:

**Comment by SirWindfield** [comment]
I went through the commit history and pinned all versions down to the right commit from back then.
